---

- name: install key
  apt_key:
    url: "{{ ROLE_NAME_apt_key_url }}"
    state: present
  register: ROLE_NAME_key_installed

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items: "{{ ROLE_NAME_apt_repositories }}"
  when: ROLE_NAME_key_installed|success
  register: ROLE_NAME_repo_installed

- name: update apt cache
  apt:
    update_cache: yes
  when: ROLE_NAME_repo_installed|changed

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: no
    update_cache:       yes
    cache_valid_time:   86400
  with_items: "{{ ROLE_NAME_packages }}"
  when: ROLE_NAME_repo_installed|success

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ROLE_NAME/{{ item }}"
  with_items:
    - ROLE_NAME.conf
  notify:
    - restart ROLE_NAME
  tags: ROLE_NAME_config

- name: service start
  service:
    name:  "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ ROLE_NAME_daemon }}"
